@Marraia.POC.Api_HostAddress = http://localhost:5017

GET {{Marraia.POC.Api_HostAddress}}/api/products
Accept: application/json

###

POST {{Marraia.POC.Api_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "Notebook",
  "price": 4500.90
}

###

### Erro 500: divisão por zero
GET {{Marraia.POC.Api_HostAddress}}/api/calculations/divide?dividend=10&divisor=0
Accept: application/json

### Erro 500: falha de conexão com o banco
GET {{Marraia.POC.Api_HostAddress}}/api/products/database
Accept: application/json

###
